### ISSUE TITLE
can't install pypcap

### ISSUE THREAD

**Issue by indianscorpion** [pynetwork/pypcap#16]
C:\app\Python27\Scripts>pip install pypcap
Collecting pypcap
  Using cached pypcap-1.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    pcap.h not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in 'folder'

**Comment by indianscorpion** [comment]
it is solved by using root user and install libpcap.

**Comment by brifordwylie** [comment]
With the 1.1.5 pip install no longer works on Macs

**Comment by hellais** [comment]
@brifordwylie is this related to #17?

**Comment by brifordwylie** [comment]
Closing this as it overlaps #17 and #20
