### ISSUE TITLE
can't install with pip3 

### ISSUE THREAD

**Issue by KaoWeiChen** [pynetwork/pypcap#19]
It can not use with python3 ?

**Comment by kings-way** [comment]
I found the problem too.....
The first error is  the function print () ....
` print "Found pcap headers in %s" % pcap_h
  
                                               ^
 
 SyntaxError: Missing parentheses in call to 'print'`

**Comment by brifordwylie** [comment]
This looks like it might be solved with PR #18. I'll test that PR.

**Comment by brifordwylie** [comment]
Closing this with PR #18, the bigger issue of general Python3 support will be addressed with #24
