### ISSUE TITLE
attribute error running setup.py for 1.1.5

### ISSUE THREAD

**Issue by dayling** [pynetwork/pypcap#20]
Found pcap headers in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/pcap/pcap.h
    Found libraries in None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-aAY0gL/pypcap/setup.py", line 59, in <module>
        lib_file = os.path.basename(lib_file_path)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 114, in basename
        i = p.rfind('/') + 1
    AttributeError: 'NoneType' object has no attribute 'rfind'

 Will attempt to debug.

**Comment by brifordwylie** [comment]
@dayling Okay I ran into the same issue. Not an expert but I ^think^ the headers are found here:
-/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/pcap/pcap.h

And the libpcap library is found here: /usr/lib/libpcap.dylib

The current 'finding' logic in setup.py will search lots of places for the headers and then uses the directory that if found pcap.h in as a root point to find the libs. Works well on linux but not with the default OSX setup. I'm making a PR that adds '/usr/lib' to the END of the directories that get searched for libs, the PR should have no negative consequences as the /usr/lib is added to the END of the search.

**Comment by brifordwylie** [comment]
closing with the merge of #23
