### ISSUE TITLE
Read the Docs (auto-docs)

### ISSUE THREAD

**Issue by brifordwylie** [pynetwork/pypcap#27]
Super Nice to have automatically generated documentation. Read the Docs is good. See (http://chains.readthedocs.io/en/latest/) for an example

**Comment by hellais** [comment]
I think this is now done and available at https://pypcap.readthedocs.io/

**Comment by hellais** [comment]
@brifordwylie I don't have access to pypcap.readthedocs.io. Did you create it? Could you grant me access to it?

My username on readthedocs.io is "hellais".

You can do that from: https://readthedocs.org/dashboard/pypcap/users/

**Comment by hellais** [comment]
This is done.
