### ISSUE TITLE
Building Cython Code

### ISSUE THREAD

**Issue by brifordwylie** [pynetwork/pypcap#30]
I have no experience with a C extension Python package, so thought I would poke around and perhaps look at some resources for making a cython package:
- http://docs.cython.org/src/quickstart/build.html
- http://docs.cython.org/src/reference/compilation.html
- https://github.com/thearn/simple-cython-example

The second link answered my previous question:
"... It is strongly recommended that you distribute the generated .c files as well as your Cython sources, so that users can install your module without needing to have Cython available...."

**Comment by nuald** [comment]
README has been updated with the Cython reference. I guess we can close this issue.

**Comment by hellais** [comment]
Yup, I also added a note about this in https://github.com/pynetwork/pypcap/pull/44/commits/53ba0c52d11c2c30258187a285c1be5d36c8df38. Will close once 1.1.6 is released.

**Comment by hellais** [comment]
This is now done.
