### ISSUE TITLE
404 pycap

### ISSUE THREAD

**Issue by khushbuparakh** [pynetwork/pypcap#40]
Docs file doesn't exist. https://github.com/pynetwork/pypcap/blob/travis-ci-integration/docs/index.rst

**Comment by hellais** [comment]
Where did you find that link? That's referencing a branch that no longer exists since it was deleted after being merged in https://github.com/pynetwork/pypcap/pull/25.

The actual file exists in the current master in the directory `doc/`

**Comment by khushbuparakh** [comment]
@hellais I found the link from read the docs of pycap module. http://pypcap.readthedocs.io/en/latest/

**Comment by hellais** [comment]
@khushbuparakh ah ok thanks.

@brifordwylie could you document the process for updating the readthedocs documentation?

**Comment by hellais** [comment]
I updated the readthedocs documentation to have `latest` point to `master`, so this should now be fixed.
