### ISSUE TITLE
Chocolatey no longer supports Npcap unfortunately 

### ISSUE THREAD

**Issue by alexwhb** [pynetwork/pypcap#55]
I was trying to install Npcap the way recommended on this project, but ran into an issue... it turns out Npcap removed their project from the Chocolatey repo unfortunately. https://github.com/nmap/nmap/issues/900

**Comment by hellais** [comment]
We have removed the line mentioning using chocolatey in the Readme. Let me know if we need to make some other changes to the readme to make it easier to set pypcap up on windows.
