### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by hellais** [pynetwork/pypcap#58]
We have a release candidate tagged here: https://github.com/pynetwork/pypcap/releases/tag/v1.2.0-rc.1.

It would be great if people were to check it out and do some testing of it to ensure nothing breaks.

Checklist for release

* [x] Ensure somebody other than me has tested it
* [x] Update docs on read-the-docs
* [x] Tag 1.2.0
* [x] Upload to pypi

**Comment by lambdalisue** [comment]
v1.2.0-rc.1 seems OK in my case. I installed it via

```
pip install git+https://github.com/pynetwork/pypcap@v1.2.0-rc.1 --ignore-installed
```

I'm looking forward to see 1.2.0 on PyPi. Thanks for your great work 😄

**Comment by hellais** [comment]
@lambdalisue thanks for reporting back on this! And apologies for taking so long to release this awaited new version.

**Comment by hellais** [comment]
Ok, this is now done. A new package has been uploaded to pypi 🎉 

Again apologies for the big delay on getting this out the door.
