### ISSUE TITLE
Mac 安装 提示：Requirement already satisfied: pypcap in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

### ISSUE THREAD

**Issue by boai** [pynetwork/pypcap#59]
Mac 安装 提示：
```
Requirement already satisfied: pypcap in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages

```

但是导入 `import pcap` 还是报错：
```
ModuleNotFoundError: No module named 'pcap'
```
求解！多谢

**Comment by xiaolushare** [comment]
你版本是3.6 然后用了master版本，你试试Python3的分支版本

**Comment by hellais** [comment]
If I understand correctly, you are having problems running pypcap with python3. We have just released a version with python 3 support, so it should now work by simply doing `pip install --upgrade pypcap`.

I am going to close this as fixed for the moment, but please report back if that is not the case.

**Comment by xiaolushare** [comment]
This fixed, THX!
