### ISSUE TITLE
Issue with libpcap

### ISSUE THREAD

**Issue by AndreTire** [pynetwork/pypcap#72]
I patched the pypcap package with the new commit; but still have the same problem. I really don't know if i mess up something. 
C:\pypcap> python setup.py install
Found pcap headers in C:\Python34\include\pcap.h
None of the following found: ['libpcap.a', 'libpcap.so', 'libpcap.dylib', 'wpcap.lib']

I installed the npcap sdk package (WinPcap has compatibility issues with Windows 10, therefore
it's recommended to use `Npcap <https://nmap.org/npcap/>) and rename the folderd as 'wpdpack', in C:\wpdpack

I use python 3.4

**Comment by guyharris** [comment]
> None of the following found: ['libpcap.a', 'libpcap.so', 'libpcap.dylib', 'wpcap.lib']

...

> I installed the npcap sdk package (WinPcap has compatibility issues with Windows 10, therefore
it's recommended to use `Npcap https://nmap.org/npcap/)

So does it include a `wpcap.lib` file, or is it called something like `npcap.lib` or `pcap.lib` or `libpcap.lib`?

> and rename the folderd as 'wpdpack', in C:\wpdpack

So what was the name *before* you renamed it?  If pypcap is looking for an SDK on Windows, in order to better support Npcap, it should look for the SDK in the location where Npcap puts it.

**Comment by AndreTire** [comment]
The file in the C:\wpdpack\Lib are wpcap.lib and the name before was 'npcap-sdk-0.1'; i just followed the steps in the pypcap/README.rst

Please clone the sources and run::

    python setup.py install

Note for Windows users: Please download the `Npcap SDK <https://nmap.org/npcap/>`_, unpack the archive and put it into the sibling directory as ``wpdpack`` (``setup.py`` will discover it).

Sample procedure in PowerShell::

    cd ..
    wget -usebasicparsing -outfile npcap-sdk-0.1.zip https://nmap.org/npcap/dist/npcap-sdk-0.1.zip
    Expand-Archive -LiteralPath npcap-sdk-0.1.zip
    mv npcap-sdk-0.1\npcap-sdk-0.1 wpdpack
    cd pypcap
    python setup.py install
