### ISSUE TITLE
New PyPI release (to include PR #8)

### ISSUE THREAD

**Issue by brifordwylie** [pynetwork/pypcap#9]
Greeting and Salutations,

The current PyPI release of pypcap basically doesn't work for network interfaces on many Macs without PR #8. I'd love to do another pypi release with the fix in it.

**Comment by hellais** [comment]
I guess what I asked in #10 should actually be discussed here.

Is this a good moment in time to perhaps define a release procedure? It doesn't have to be anything particularly fancy, but just specifying some basic criteria by which we say the code is in good quality to make a new release and what are the steps required to cut it (tag the git repo with a certain semantic, push a gpg signed tarbal to pypi, etc.).

**Comment by brifordwylie** [comment]
Arturo,

If you want I'll add a setup.cfg script that allows us to just do a $python
setup.py release  with a gpg signature...

-bri

**Comment by hellais** [comment]
That would be great. Go for it!
