### ISSUE TITLE
ERROR: Failed building wheel for pypcap

### ISSUE THREAD

**Issue by frostKn** [pynetwork/pypcap#98]
I have been having issues installing pypcap on parrot os 5.6.0,
sorry I am new to this all attached along is the log, 
any help would be appreciated

[err.log](https://github.com/pynetwork/pypcap/files/4941570/err.log)

**Comment by frostKn** [comment]
I was just missing some prerequisites ..for those having the same issue this is what I did 

`sudo apt-get install build-essential libssl-dev libffi-dev python-dev gcc-9-base`

**Comment by code-0802** [comment]
@frostKn I have tried you suggestion. But still I am facing the same error.
Here is my error log 
[pypcap_error.log](https://github.com/pynetwork/pypcap/files/6323200/pypcap_error.log)
